arangodb:
  image: arangodb/arangodb
  #build: ./dockerfiles
  command: arangod
  #command: arangod --server.storage-engine rocksdb
  container_name: arangodb
  ports:
    - 8529:8529
  volumes:
    #- ./arangodb3/:/var/lib/arangodb3
    #- ./arangodb3-apps:/var/lib/arangodb3-apps
    - ./splitted:/splitted
    - ./parsed:/parsed
    - ./scripts:/scripts
    - ./config.js:/config.js
  environment:
    #ARANGO_RANDOM_ROOT_PASSWORD: 1
    ARANGO_ROOT_PASSWORD: 'wikidatarocks'
    #ARANGO_STORAGE_ENGINE: rocksdb
